import type { Metadata } from "next";
import { Inter, Manrope} from "next/font/google";
import "./globals.css";

// const inter = Inter({ subsets: ["latin"],variable: '--font-manrope', });

const manrop = Manrope({ subsets: ["latin"],variable: '--font-manrope',weight:"500", style:"normal" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${manrop.variable} font-sans bg-main-bg`}>
        {children}
        <div id="modal-root"></div>
        </body>
    </html>
  );
}
